services:
  web:
    build:
      context: .
      target: build
    image: your-image-name:latest
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - BUNDLE_DEPLOYMENT=1
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_WITHOUT=development
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-e", "production"]
